Param(
        [Parameter(Mandatory=$true)]
        $Spoke,
        [Parameter(Mandatory=$true)]
        $Identifier,
        [Parameter(Mandatory=$true)]
        $HubIdentifier,
        [Parameter(Mandatory=$true)]
        $HubRG,
        [Parameter(Mandatory=$true)]
        $DeployFirewalls,
        [Parameter(Mandatory=$false)]
        $FirewallIP,
        [Parameter(Mandatory=$true)]
        $RGName,
        [Parameter(Mandatory=$true)]
        $location,
        [Parameter(Mandatory=$false)]
        $FirewallHubSubnetIdentifier
    )